# Generated by Django 5.2.18 on 2026-10-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed_by', models.DateTimeField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('pickup_point', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('purchased', 'Purchased'), ('handed_over', 'Handed Over'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('expected_total', models.PositiveIntegerField(help_text="Customer's guess. NEVER charged.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handover_code', models.CharField(blank=True, max_length=12)),
                ('customer_handover_confirmed', models.BooleanField(default=False)),
                ('helper_handover_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('expected_price', models.PositiveIntegerField()),
                ('actual_price', models.PositiveIntegerField(blank=True, null=True)),
                ('price_approved', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('alternatives_allowed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('found', 'Found'), ('unavailable', 'Unavailable'), ('replaced', 'Replaced')], default='pending', max_length=20)),
                ('replacement_proposal', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('purchased', 'Purchased'), ('handed_over', 'Handed Over'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('purchased', 'Purchased'), ('handed_over', 'Handed Over'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
