# Generated by Django 5.2.18 on 2026-10-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('held', 'Held'), ('released', 'Released'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='none', max_length=20)),
                ('item_cost', models.PositiveIntegerField(help_text='ACTUAL confirmed price — never the guess')),
                ('helper_fee', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('provider', models.CharField(default='manual', max_length=20)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('customer_confirmed', models.BooleanField(default=False)),
                ('helper_confirmed', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.request')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='payments.payment')),
            ],
        ),
    ]
